function ezoutput1(filename_pre_texture,filename_pre_noise,num,threshold_texture,threshold_noise,texture_probthr,noise_probthr)
% num = 14;
% threshold_texture = 0.45;
% threshold_noise = 0.45;
% texture_probthr = 0.018;
% noise_probthr = 0.001;
image_texture = imagestackRead(filename_pre_texture{num},1);
image_noise = imagestackRead(filename_pre_noise{num},0);
patch_texture = computePatch(image_texture,1000,threshold_texture);
patch_noise = computePatch(image_noise,1000,threshold_noise);
prob_texture = edgeprob(patch_texture);
prob_noise = edgeprob(patch_noise);
matrix_texture = matrixmaker(patch_texture,prob_texture,texture_probthr);
[output_texture,eigenvector_texture,eigenvalue_texture] = computeThirdOrderEmbed(matrix_texture);
figure;
subplot(2,4,1);
imshow(image_texture(:,:,1));title(strcat(filename_pre_texture{num},'# of patches:',num2str(size(patch_texture,4))));
subplot(2,4,5);
imshow(image_noise(:,:,1));title(strcat(filename_pre_noise{num},'# of patches:',num2str(size(patch_noise,4))));
subplot(2,4,2);
plot(prob_texture);
subplot(2,4,3);
temp = diag(eigenvalue_texture);
temp = flipud(temp);
plot(temp);title(strcat('thr: ',num2str(threshold_texture)));
subplot(2,4,4);
scatter3(output_texture(:,1),output_texture(:,2),output_texture(:,3),14,ones(size(output_texture(:,1))),'filled');title(strcat('prob thr: ',num2str(texture_probthr)));
matrix_noise = matrixmaker(patch_noise,prob_noise,noise_probthr);
[output_noise,eigenvector_noise,eigenvalue_noise] = computeThirdOrderEmbed(matrix_noise);
subplot(2,4,6);
plot(prob_noise);
subplot(2,4,7);
temp = diag(eigenvalue_noise);
temp = flipud(temp);
plot(temp);title(strcat('thr: ',num2str(threshold_noise)));
subplot(2,4,8);
scatter3(output_noise(:,1),output_noise(:,2),output_noise(:,3),14,ones(size(output_noise(:,1))),'filled');title(strcat('prob thr: ',num2str(noise_probthr)));